### PR TITLE
fix: add @typescript-eslint/no-redeclare

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by martinheidegger** [comment]
Since this commit I am getting this error message in my package: `Definition for rule '@typescript-eslint/no-redeclare' was not found.eslint(@typescript-eslint/no-redeclare)`

**Comment by 07akioni** [comment]
> Since this commit I am getting this error message in my package: `Definition for rule '@typescript-eslint/no-redeclare' was not found.eslint(@typescript-eslint/no-redeclare)`

Same problem

**Comment by mightyiam** [comment]
Make sure you have the correct version of `@typescript-eslint/eslint-plugin`, as specified by the `peerDependencies` of this package.

**Comment by evsar3** [comment]
I got the same problem as @martinheidegger and @07akioni 
Please see issue #450

**Comment by alexandradeas** [comment]
This appears to be caused by the readme recommending an out of date version of `@typescript-eslint/eslint-plugin`. Changing that version to 4 resolves the issue

**Pull request merged**
