### PR TITLE
fix: [dot-notation] explicitly redefine the rule

### PR DESCRIPTION
**Pull request by andrefilimono**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[X] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

The rule **@typescript-eslint/dot-notation** is explicitly defined now.

**Which issue (if any) does this pull request address?**

#303 

**Is there anything you'd like reviewers to focus on?**

No

### CODE REVIEW

**Comment by LinusU** [comment]
Hmmm, I don't see how this will fix the problem, have you verified that it does?

As you can see in `src/index.test.ts`, the output hasn't really changed, and we were already using `@typescript-eslint/dot-notation`, and the normal `dot-notation` was turned off...

**Comment by LinusU** [comment]
I added my comment on what I think the problem is here: https://github.com/typescript-eslint/typescript-eslint/issues/2047#issuecomment-631320530

**Comment by andrefilimono** [comment]
I spent some time to debug the internals of `@typescript-eslint`, it works as expected and ESLint applies the correct `@typescript-eslint/dot-notation` rule in runtime.

But when it comes down to the `eslint-config-standard-with-typescript` I see that ESLint uses the wrong rule `dot-notation` instead of `@typescript-eslint/dot-notation`. 
But when I apply changes from this PR it starts using the correct one. 
Actually I don't know why, but it just works.

**Comment by LinusU** [comment]
Hmmm, this is super weird. If I modify both `.eslintrc.json` and `__tests__/.eslintrc.json` to be exactly the same, and then run `npm run lint:eslint` I get the error. If I then remove `__tests__/.eslintrc.json` the error goes away 🤔 

in this repo: https://github.com/BrainJS/brain.js

**Pull request closed without merging**
