### PR TITLE
docs: update the link to ESLint --ext option in readme

### PR DESCRIPTION
**Pull request by Wintus**
**What is the purpose of this pull request? (put an "X" next to item)**

[X] Documentation update
[ ] Bug fix
[ ] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

I just fix the broken link.

### CODE REVIEW

**Comment by Wintus** [comment]
I see. I'll force push to overwrite or somehow manage it out.

**Comment by mightyiam** [comment]
On your local branch

```
$ git commit --amend
$ git push --force
```

**Comment by Wintus** [comment]
now it's passed.

**Comment by mightyiam** [comment]
Thank you, @Wintus!

**Pull request merged**
