### PR TITLE
chore: update deps and change Travis to GitHub actions + add dependabot

### PR DESCRIPTION
**Pull request by Divlo**
**What changes did you make? (Give an overview)**

- Add `.github/dependabot.yml`
- Add `.github/workflows/nodejs.yml`
- Add `.github/workflows/commitlint.yml`
- Delete `.travis.yml`
- Update `README` with the new badge
- Update `husky@5`
- Update to latest version every dependencies except `@typescript-eslint/eslint-plugin`, because with latest version, the tests are failing
- Change `commitlint-config-awesome` to `@commitlint/config-conventional`
`commitlint-config-awesome` is less used/updated (not updated since Dec 16, 2019), break on `npm@7` because peerDependency don't match and we don't need it anymore because we don't use anymore `Greenkeeper`, also `@commitlint/config-conventional` is what it is used for `ts-standard`.

**Which issue (if any) does this pull request address?**

Closes #525, closes #524, closes #516

**Is there anything you'd like reviewers to focus on?**

We should remove the stale branches from the old Greenkeeper bot and renovatebot once this has been merged.
We should also change branch protection rules so, we don't rely anymore on Travis runs for PRs.

### CODE REVIEW

**Comment by mightyiam** [comment]
I appreciate the effort, @Divlo. Could you please break this into separate minimal pull requests, so that I could easily review them one at a time?

**Comment by Divlo** [comment]
There is not that much going on.
It just replace `travis` by `GitHub Actions` and updated the dependencies.
Could you tell me how I could seperate this in multiple PRs, I don't think it is viable to open a PR for every file I change.

I thought of something like that :
- PR to update `husky`
- PR to replace `travis` to `GitHub Actions` (+ `dependabot`)
- PR to update every dependencies + change `commitlint-config-awesome` to `@commitlint/config-conventional`

Is it better like this? :smile: @mightyiam

**Comment by mightyiam** [comment]
Figuring out what is going on is not a challenge. It's only somewhat more of an inconvenience. Also, I do my best to uphold great git practice. I expect that from others when it's a project I feel somewhat responsible for.

I appreciate the cooperation.

I would also separate between the dependency upgrades and the commitlint-config dep change.

Also, why don't you let the dependabot thing upgrade deps, instead of you?

**Comment by Divlo** [comment]
> Also, why don't you let the dependabot thing upgrade deps, instead of you?

I never used `renovabot`, but it seems like it sometime take some time to merge the PRs.
As for `dependabot`, as far as I know, it is not included with it, we must merge manually the PRs.
The advantage to merge manually the PR is to see the changelog, see what changes, etc.

If you rather to update the dependencies automatically, we could stay with `renovabot`, I wanted to migrate to `dependabot` because it is the thing made by GitHub, so in my opinion it is better integrated and also that it is what we use for `standard`, `standard-engine` and `ts-standard`.

**Comment by mightyiam** [comment]
> > Also, why don't you let the dependabot thing upgrade deps, instead of you?
> 
> I never used `renovabot`, but it seems like it sometime take some time to merge the PRs.

Perhaps you've assumed that merging is automatic? It's not.

> As for `dependabot`, as far as I know, it is not included with it, we must merge manually the PRs.
> The advantage to merge manually the PR is to see the changelog, see what changes, etc.

Yup. Same as currently, with renovate.
> 
> If you rather to update the dependencies automatically, we could stay with `renovabot`, I wanted to migrate to `dependabot` because it is the thing made by GitHub, so in my opinion it is better integrated and also that it is what we use for `standard`, `standard-engine` and `ts-standard`.

I wouldn't mind. Yet, I'd like it in a PR that is dedicated to that change.

**Comment by Divlo** [comment]
> Perhaps you've assumed that merging is automatic? It's not.

I thought it was automatic yes, since in the PRs description of `renovatebot` there is "Automerge: Enabled." and that I saw some PRs merged automatically like this one : #413 

@mightyiam I will close this PR since I opened this PR as few multiple PRs, hopefully it's easier to review, thanks for your help! :smile: 
- https://github.com/standard/eslint-config-standard-with-typescript/pull/529
- https://github.com/standard/eslint-config-standard-with-typescript/pull/530
- https://github.com/standard/eslint-config-standard-with-typescript/pull/531
- https://github.com/standard/eslint-config-standard-with-typescript/pull/532
- https://github.com/standard/eslint-config-standard-with-typescript/pull/533

**Comment by mightyiam** [comment]
Perhaps I was wrong about renovate not auto-merging. We'll see in the individual PRs.

**Pull request closed without merging**
