### PR TITLE
feat: use @typescript-eslint func-call-spacing equivalent

### PR DESCRIPTION
**Pull request by felskov**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Replaced eslint default func-call-spacing with @typescript-eslint/func-call-spacing

**Which issue (if any) does this pull request address?**
#232 

**Is there anything you'd like reviewers to focus on?**
No

### CODE REVIEW

**Comment by mightyiam** [comment]
@felskov thank you for the PR. One question. Did you manually test that this solves #232, please?

**Comment by felskov** [comment]
@mightyiam Yes, I added the following code to `fixture.ts` and ran `npm run lint` prior to and after implementing the change, and can confirm that issues are no longer reported.

```ts
export const map = new Map<string, () => void>()
```

**Comment by mightyiam** [comment]
Another question, please, @felskov. Do you think that this could trigger any new lint errors for users that upgrade? If so, then the commit message should include the "BREAKING CHANGE: blah blah" pattern, please. And it would also be nice to have the "fixes #issuenumber" part in the commit message, please. See commit log for reference.

**Comment by LinusU** [comment]
Great work! 👏 

> Do you think that this could trigger any new lint errors for users who upgrade?

My guess is that it shouldn't, since the previous rule simply didn't understand the extra type parameters 🤔

**Comment by felskov** [comment]
@mightyiam To the best of my knowledge the @typescript-eslint equivalent is a drop-in replacement for the eslint built-in rule, just adding support for syntax the original rule doesn't understand.

Should I amend the commit message to reference the issue and push an update?

**Comment by mightyiam** [comment]
In the docs for the rule it says

> This version adds support for generic type parameters on function calls

Perhaps introducing this rule could trigger linting errors on generic type parameters on function calls?

Seems to me like a breaking change. Like:

```
BREAKING CHANGE: new rule @typescript-eslint/func-call-spacing
```

And yes, @felskov. Please add the "fixes" reference, as well.

**Comment by felskov** [comment]
@mightyiam No problem, I've amended the message as requested

**Comment by mightyiam** [comment]
Thank you so much!

**Pull request merged**
