### PR TITLE
fix: disable `no-implied-eval` rule of eslint

### PR DESCRIPTION
**Pull request by zanminkian**
**What is the purpose of this pull request? (put an "X" next to item)**

[x] Documentation update
[x] Bug fix
[ ] New feature
[x] Other, please explain:
This config forget to disable `no-implied-eval`. See: https://typescript-eslint.io/rules/no-implied-eval/

**What changes did you make? (Give an overview)**

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Review by LinusU — APPROVED** [review]
Nice catch 👍

**Comment by mightyiam** [comment]
I'll take a look.

**Comment by zanminkian** [comment]
Hi @mightyiam, I've fix the test. Now it pass. Please take a review. :)

**Comment by mightyiam** [comment]
This kind of bug should not occur. Could you identify the test that is supposed to make sure this kind of bug cannot occur and see whether you're able to fix it?

**Comment by mightyiam** [comment]
And if you do, could you submit a draft pull requests that only fixes that test? It should be failing then.

**Comment by jay-bulk** [comment]
closed by #1292

**Comment by jay-bulk** [comment]
Thanks for the PR!

**Pull request closed without merging**
